In [1]:
print ("My Hospital analytics project has started")

My Hospital analytics project has started

In [6]:
from pathlib import Path

print(Path("data/raw/csv/patients.csv").exists())

False

In [7]:
from pathlib import Path

print(Path.cwd())

c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\notebooks

In [8]:
from pathlib import Path

print(Path.cwd().parent)
print(Path.cwd().parent.parent)

c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics
c:\Users\HP\OneDrive\Documents\Programming Portfolio

In [9]:
from pathlib import Path

patient_file = Path("../data/raw/csv/patients.csv")
print(patient_file.exists())

True

In [10]:
import pandas as pd
from pathlib import Path

patient_file = Path("../data/raw/csv/patients.csv")
patients = pd.read_csv(patient_file)

print(patients.head())

                                     Id   BIRTHDATE DEATHDATE          SSN  \
0  b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85  2019-02-17       NaN  999-65-3251
1  c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8  2005-07-04       NaN  999-49-3323
2  339144f8-50e1-633e-a013-f361391c4cff  1998-05-11       NaN  999-10-8743
3  d488232e-bf14-4bed-08c0-a82f34b6a197  2003-01-28       NaN  999-56-6057
4  217f95a3-4e10-bd5d-fb67-0cfb5e8ba075  1993-12-23       NaN  999-91-4320

     DRIVERS    PASSPORT PREFIX       FIRST            LAST SUFFIX  ...  \
0        NaN         NaN    NaN    Damon455      Langosh790    NaN  ...
1  S99941126         NaN    NaN       Thi53       Wunsch504    NaN  ...
2  S99996708  X75063318X    Mr.      Chi716  Greenfelder433    NaN  ...
3  S99929424         NaN    Ms.  Phillis443       Walter473    NaN  ...
4  S99991143  X44132498X    Mr.  Jerrold404       Herzog843    NaN  ...

                         BIRTHPLACE                           ADDRESS  \
0  Middleborough  Massachusetts  US            620 Lynch Tunnel Apt 0
1        Danvers  Massachusetts  US       972 Tillman Branch Suite 48
2     Athens  Athens Prefecture  GR  1060 Bernhard Crossroad Suite 15
3         Boston  Massachusetts  US               677 Ritchie Terrace
4         Boston  Massachusetts  US                276 Bernier Branch

          CITY          STATE           COUNTY     ZIP        LAT        LON  \
0  Springfield  Massachusetts   Hampden County  1104.0  42.080389 -72.480431
1   Bellingham  Massachusetts   Norfolk County     NaN  42.035213 -71.482519
2       Boston  Massachusetts   Suffolk County  2131.0  42.292557 -71.061160
3      Hingham  Massachusetts  Plymouth County  2043.0  42.200491 -70.916076
4       Revere  Massachusetts   Suffolk County     NaN  42.381875 -70.999286

  HEALTHCARE_EXPENSES HEALTHCARE_COVERAGE
0           9039.1645           7964.1255
1         402723.4150          14064.1350
2         571935.8725            787.5375
3         582557.8030         104782.2070
4         475826.8550          18067.0950

[5 rows x 25 columns]

In [12]:
print("Dataset shape:", patients.shape)
print("\nColumn names:")
print(patients.columns.tolist())

Dataset shape: (1163, 25)

Column names:
['Id', 'BIRTHDATE', 'DEATHDATE', 'SSN', 'DRIVERS', 'PASSPORT', 'PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE', 'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE', 'COUNTY', 'ZIP', 'LAT', 'LON', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE']

In [13]:
print("Missing values per column:")
print(patients.isnull().sum())

Missing values per column:
Id                        0
BIRTHDATE                 0
DEATHDATE              1000
SSN                       0
DRIVERS                 215
PASSPORT                276
PREFIX                  245
FIRST                     0
LAST                      0
SUFFIX                 1147
MAIDEN                  832
MARITAL                 384
RACE                      0
ETHNICITY                 0
GENDER                    0
BIRTHPLACE                0
ADDRESS                   0
CITY                      0
STATE                     0
COUNTY                    0
ZIP                     545
LAT                       0
LON                       0
HEALTHCARE_EXPENSES       0
HEALTHCARE_COVERAGE       0
dtype: int64

In [14]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 1163 entries, 0 to 1162
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   1163 non-null   str
 1   BIRTHDATE            1163 non-null   str
 2   DEATHDATE            163 non-null    str
 3   SSN                  1163 non-null   str
 4   DRIVERS              948 non-null    str
 5   PASSPORT             887 non-null    str
 6   PREFIX               918 non-null    str
 7   FIRST                1163 non-null   str
 8   LAST                 1163 non-null   str
 9   SUFFIX               16 non-null     str
 10  MAIDEN               331 non-null    str
 11  MARITAL              779 non-null    str
 12  RACE                 1163 non-null   str
 13  ETHNICITY            1163 non-null   str
 14  GENDER               1163 non-null   str
 15  BIRTHPLACE           1163 non-null   str
 16  ADDRESS              1163 non-null   str
 17  CITY                 1163 non-null   str
 18  STATE                1163 non-null   str
 19  COUNTY               1163 non-null   str
 20  ZIP                  618 non-null    float64
 21  LAT                  1163 non-null   float64
 22  LON                  1163 non-null   float64
 23  HEALTHCARE_EXPENSES  1163 non-null   float64
 24  HEALTHCARE_COVERAGE  1163 non-null   float64
dtypes: float64(5), str(20)
memory usage: 227.3 KB

In [15]:
print("Duplicate rows:", patients.duplicated().sum())

print("Duplicate patient IDs:", patients["Id"].duplicated().sum())

Duplicate rows: 0
Duplicate patient IDs: 0

In [16]:
print("Birthdate examples:")
print(patients["BIRTHDATE"].head())

print("\nDeathdate examples:")
print(patients["DEATHDATE"].head(10))

Birthdate examples:
0    2019-02-17
1    2005-07-04
2    1998-05-11
3    2003-01-28
4    1993-12-23
Name: BIRTHDATE, dtype: str

Deathdate examples:
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
Name: DEATHDATE, dtype: str

In [17]:
print("Birthdate data type:", patients["BIRTHDATE"].dtype)
print("Deathdate data type:", patients["DEATHDATE"].dtype)

print("\nPatients with a recorded deathdate:")
print(patients["DEATHDATE"].notna().sum())

print("\nPatients without a recorded deathdate:")
print(patients["DEATHDATE"].isna().sum())

print("\nUnique gender values:")
print(patients["GENDER"].value_counts(dropna=False))

Birthdate data type: str
Deathdate data type: str

Patients with a recorded deathdate:
163

Patients without a recorded deathdate:
1000

Unique gender values:
GENDER
F    616
M    547
Name: count, dtype: int64

In [21]:
#Check the range of patient birthdates
print("Earliest birthdate:") 
print(patients["BIRTHDATE"].min())
print("\nLatest birthdate:") 
print(patients["BIRTHDATE"].max())
#Check for birthdates that cannot be parsed
birthdates = pd.to_datetime( patients["BIRTHDATE"], errors="coerce" )
print("\nUnparseable birthdates:") 
print(birthdates.isna().sum())
#Check the birthdate range after conversion
print("\nEarliest parsed birthdate:") 
print(birthdates.min())
print("\nLatest parsed birthdate:") 
print(birthdates.max())

Earliest birthdate:
1911-07-14

Latest birthdate:
2021-09-24

Unparseable birthdates:
0

Earliest parsed birthdate:
1911-07-14 00:00:00

Latest parsed birthdate:
2021-09-24 00:00:00

In [24]:
#Convert date columns to datetime
patients["BIRTHDATE"] = pd.to_datetime( patients["BIRTHDATE"], errors="coerce" )
patients["DEATHDATE"] = pd.to_datetime( patients["DEATHDATE"], errors="coerce" )
#Check the results
print("Birthdate data type:", patients["BIRTHDATE"].dtype) 
print("Deathdate data type:", patients["DEATHDATE"].dtype)
print("\nEarliest birthdate:", patients["BIRTHDATE"].min()) 
print("Latest birthdate:", patients["BIRTHDATE"].max())
print("\nRecorded death dates:", patients["DEATHDATE"].notna().sum())

Birthdate data type: datetime64[us]
Deathdate data type: datetime64[us]

Earliest birthdate: 1911-07-14 00:00:00
Latest birthdate: 2021-09-24 00:00:00

Recorded death dates: 163

In [27]:
#Convert date columns to datetime
patients["BIRTHDATE"] = pd.to_datetime( patients["BIRTHDATE"], errors="coerce" )
patients["DEATHDATE"] = pd.to_datetime( patients["DEATHDATE"], errors="coerce" )
#Check the results
print("Birthdate data type:", patients["BIRTHDATE"].dtype) 
print("Deathdate data type:", patients["DEATHDATE"].dtype)
print("\nEarliest birthdate:", patients["BIRTHDATE"].min()) 
print("Latest birthdate:", patients["BIRTHDATE"].max())
print("\nRecorded death dates:", patients["DEATHDATE"].notna().sum())

Birthdate data type: datetime64[us]
Deathdate data type: datetime64[us]

Earliest birthdate: 1911-07-14 00:00:00
Latest birthdate: 2021-09-24 00:00:00

Recorded death dates: 163

In [28]:
missing_summary = pd.DataFrame({
    "Missing_Count": patients.isnull().sum(),
    "Missing_Percentage": (
        patients.isnull().sum() / len(patients) * 100
    ).round(2)
})

missing_summary = missing_summary.sort_values(
    "Missing_Percentage", ascending=False
)

print(missing_summary)

                     Missing_Count  Missing_Percentage
SUFFIX                        1147               98.62
DEATHDATE                     1000               85.98
MAIDEN                         832               71.54
ZIP                            545               46.86
MARITAL                        384               33.02
PASSPORT                       276               23.73
PREFIX                         245               21.07
DRIVERS                        215               18.49
Id                               0                0.00
LAST                             0                0.00
FIRST                            0                0.00
BIRTHDATE                        0                0.00
SSN                              0                0.00
ETHNICITY                        0                0.00
GENDER                           0                0.00
BIRTHPLACE                       0                0.00
RACE                             0                0.00
ADDRESS                          0                0.00
CITY                             0                0.00
STATE                            0                0.00
COUNTY                           0                0.00
LAT                              0                0.00
LON                              0                0.00
HEALTHCARE_EXPENSES              0                0.00
HEALTHCARE_COVERAGE              0                0.00

In [29]:
#Check for birthdates occurring after recorded deathdates
invalid_dates = patients[ patients["DEATHDATE"].notna() & (patients["BIRTHDATE"] > patients["DEATHDATE"]) ]
print("Records with death before birth:", len(invalid_dates))

Records with death before birth: 0

In [30]:
#Calculate patient age at the time of death, where applicable
reference_date = pd.Timestamp("2026-10-27")
patients["AGE"] = ( reference_date - patients["BIRTHDATE"] ).dt.days / 365.25
patients["AGE"] = patients["AGE"].round(1)
print("Age summary:") 
print(patients["AGE"].describe())

Age summary:
count    1163.000000
mean       49.941788
std        27.575042
min         5.100000
25%        27.050000
50%        48.700000
75%        67.900000
max       115.300000
Name: AGE, dtype: float64

In [31]:
#Identify patients aged 100 or older
very_old_patients = patients[patients["AGE"] >= 100]
print("Patients aged 100 or older:", len(very_old_patients))
print("\nTheir birthdates:") 
print(very_old_patients[["BIRTHDATE", "AGE"]])

Patients aged 100 or older: 78

Their birthdates:
      BIRTHDATE    AGE
252  1924-12-04  101.9
329  1926-07-19  100.3
346  1926-07-19  100.3
366  1926-07-19  100.3
378  1926-07-19  100.3
...         ...    ...
1080 1912-10-07  114.1
1081 1923-09-06  103.1
1096 1912-10-07  114.1
1099 1911-11-04  115.0
1117 1912-10-07  114.1

[78 rows x 2 columns]

In [32]:
#Check death-date information for patients aged 100 or older
print("Patients aged 100+:", len(very_old_patients))
print( "Patients aged 100+ with recorded death dates:", very_old_patients["DEATHDATE"].notna().sum() )
print( "Patients aged 100+ without recorded death dates:", very_old_patients["DEATHDATE"].isna().sum() )

Patients aged 100+: 78
Patients aged 100+ with recorded death dates: 61
Patients aged 100+ without recorded death dates: 17

In [33]:
#Investigate patients aged 100 or older
very_old_patients = patients[patients["AGE"] >= 100]
print("Age range of patients aged 100+:") 
print(very_old_patients["AGE"].describe())
print("\nAge distribution of patients aged 100+:") 
print(very_old_patients["AGE"].value_counts().sort_index())
print("\nCheck for duplicate patient IDs:") 
print("Duplicate IDs:", patients["Id"].duplicated().sum())

Age range of patients aged 100+:
count     78.000000
mean     109.300000
std        5.103246
min      100.000000
25%      107.275000
50%      110.600000
75%      113.400000
max      115.300000
Name: AGE, dtype: float64

Age distribution of patients aged 100+:
AGE
100.0     8
100.3     5
101.9     1
103.1     1
104.9     3
107.1     2
107.8     4
107.9     5
109.5     8
110.6     6
111.9     6
113.3     2
113.4    11
114.1     7
115.0     7
115.3     2
Name: count, dtype: int64

Check for duplicate patient IDs:
Duplicate IDs: 0

In [34]:
#Investigate patients aged 100 or older
very_old_patients = patients[patients["AGE"] >= 100].copy()
print("Patients aged 100+: ", len(very_old_patients))
print("\nAge and birthdate of oldest patients:") 
print( very_old_patients[ ["Id", "BIRTHDATE", "DEATHDATE", "AGE"] ].sort_values("AGE", ascending=False).head(15) )

Patients aged 100+:  78

Age and birthdate of oldest patients:
                                        Id  BIRTHDATE  DEATHDATE    AGE
526   7f4ecb1c-eb6f-f819-0d42-b86912ee0d38 1911-07-14 1994-11-26  115.3
549   7bc66758-5d59-0b38-1532-29a33fa146c1 1911-07-14        NaT  115.3
1061  3c26a41e-d1a5-45ed-6956-09bcefe3c08c 1911-11-04 1961-08-29  115.0
1029  33ee607c-5afa-d4ff-85bc-3191531cf8c1 1911-11-04 1989-09-07  115.0
1044  b1d84e5c-1c09-c772-2ee1-ca095df0d435 1911-11-04 1996-12-09  115.0
1078  7a9c0e7a-c835-7b68-101d-190ddf573df9 1911-11-04 2007-07-04  115.0
1014  37ab5291-cc03-1798-2097-d35809156954 1911-11-04 1992-09-29  115.0
1053  45a3f02c-149e-c09f-ca71-be5d33481bbb 1911-11-04 1975-06-21  115.0
1099  6a5b7896-78b9-2b39-0219-a618a7562372 1911-11-04        NaT  115.0
1117  073967cc-9195-3de9-8ce1-e0cd81461da4 1912-10-07        NaT  114.1
1063  6d448f13-ee6d-61a4-2123-a32120b274ae 1912-10-07 2007-05-30  114.1
1080  b6a7f9cd-340d-4289-ef69-12fdc928ad30 1912-10-07 2016-03-21  114.1
1096  6bdd9c1a-17be-8543-322f-91786c6af444 1912-10-07 2001-09-05  114.1
1047  abbfa35f-d330-3e74-cfba-5c0ad5a2166b 1912-10-07 1981-02-28  114.1
1033  8bf91de1-4c40-442e-fc72-ca32b63a9d08 1912-10-07 1981-02-08  114.1

In [35]:
#Compare recorded ages with ages calculated from birthdates
reference_date = patients["BIRTHDATE"].max()
print("Latest birthdate in dataset:", reference_date) 
print("\nSample of patients aged 100+:")
print( very_old_patients[ ["BIRTHDATE", "DEATHDATE", "AGE"] ].head(10) )

Latest birthdate in dataset: 2021-09-24 00:00:00

Sample of patients aged 100+:
     BIRTHDATE  DEATHDATE    AGE
252 1924-12-04        NaT  101.9
329 1926-07-19 1997-01-05  100.3
346 1926-07-19 2010-06-02  100.3
366 1926-07-19 2020-05-01  100.3
378 1926-07-19 1995-09-06  100.3
392 1926-07-19        NaT  100.3
411 1913-06-22        NaT  113.3
420 1914-12-20 2009-08-22  111.9
431 1914-12-20 1984-09-02  111.9
443 1914-12-20 1981-09-25  111.9

In [36]:
#Check whether recorded death dates occur before age 100
very_old_patients["100th_birthday"] = ( very_old_patients["BIRTHDATE"] + pd.DateOffset(years=100) )
death_before_100 = very_old_patients[ very_old_patients["DEATHDATE"].notna() & ( very_old_patients["DEATHDATE"] < very_old_patients["100th_birthday"] ) ]
print( "Patients aged 100+ with death dates before " "their 100th birthday:", len(death_before_100) )
print("\nSample records to investigate:")
print( death_before_100[ ["BIRTHDATE", "DEATHDATE", "AGE", "100th_birthday"] ].head(10) )

Patients aged 100+ with death dates before their 100th birthday: 60

Sample records to investigate:
     BIRTHDATE  DEATHDATE    AGE 100th_birthday
329 1926-07-19 1997-01-05  100.3     2026-07-19
346 1926-07-19 2010-06-02  100.3     2026-07-19
366 1926-07-19 2020-05-01  100.3     2026-07-19
378 1926-07-19 1995-09-06  100.3     2026-07-19
420 1914-12-20 2009-08-22  111.9     2014-12-20
431 1914-12-20 1984-09-02  111.9     2014-12-20
443 1914-12-20 1981-09-25  111.9     2014-12-20
460 1914-12-20 1990-06-19  111.9     2014-12-20
474 1914-12-20 1998-07-13  111.9     2014-12-20
526 1911-07-14 1994-11-26  115.3     2011-07-14

In [37]:
#Investigate age inconsistencies
#Calculate age at death for patients with recorded death dates
has_death_date = patients["DEATHDATE"].notna()
patients_with_death = patients.loc[has_death_date].copy()
patients_with_death["AGE_AT_DEATH"] = ( (patients_with_death["DEATHDATE"] - patients_with_death["BIRTHDATE"]) .dt.days / 365.2425 ).round(1)
#Compare the recorded AGE with calculated age at death
patients_with_death["AGE_DIFFERENCE"] = ( patients_with_death["AGE"] - patients_with_death["AGE_AT_DEATH"] ).round(1)
print("Patients with recorded death dates:", len(patients_with_death))
print("\nSample of age comparisons:") 
print( patients_with_death[ ["BIRTHDATE", "DEATHDATE", "AGE", "AGE_AT_DEATH", "AGE_DIFFERENCE"] ].head(10) )

Patients with recorded death dates: 163

Sample of age comparisons:
     BIRTHDATE  DEATHDATE   AGE  AGE_AT_DEATH  AGE_DIFFERENCE
14  1958-09-18 2009-11-13  68.1          51.2            16.9
27  1969-01-03 1997-02-17  57.8          28.1            29.7
58  1969-10-19 2005-11-09  57.0          36.1            20.9
70  1942-10-15 1996-05-12  84.0          53.6            30.4
73  1958-04-07 2011-07-10  68.6          53.3            15.3
78  1942-10-15 1993-01-06  84.0          50.2            33.8
82  1948-03-03 2008-06-21  78.7          60.3            18.4
83  1944-02-16 2019-10-10  82.7          75.6             7.1
98  1970-10-24 1995-11-07  56.0          25.0            31.0
124 1955-02-02 2021-07-07  71.7          66.4             5.3

In [38]:
#Count differences between recorded age and age at death
print("Age difference summary:") 
print(patients_with_death["AGE_DIFFERENCE"].describe())
#Count records where the difference exceeds one year
inconsistent_ages = patients_with_death[ patients_with_death["AGE_DIFFERENCE"].abs() > 1 ]
print( "\nRecords with age differences greater than 1 year:", len(inconsistent_ages) )
print( "Percentage of patients with recorded death dates:", round(len(inconsistent_ages) / len(patients_with_death) * 100, 2), "%" )
#Display a sample of inconsistent records
print("\nSample inconsistent records:") 
print( inconsistent_ages[ ["BIRTHDATE", "DEATHDATE", "AGE", "AGE_AT_DEATH", "AGE_DIFFERENCE"] ].head(10) )

Age difference summary:
count    163.000000
mean      26.242945
std       16.356069
min        5.100000
25%       14.100000
50%       23.400000
75%       35.500000
max       84.900000
Name: AGE_DIFFERENCE, dtype: float64

Records with age differences greater than 1 year: 163
Percentage of patients with recorded death dates: 100.0 %

Sample inconsistent records:
     BIRTHDATE  DEATHDATE   AGE  AGE_AT_DEATH  AGE_DIFFERENCE
14  1958-09-18 2009-11-13  68.1          51.2            16.9
27  1969-01-03 1997-02-17  57.8          28.1            29.7
58  1969-10-19 2005-11-09  57.0          36.1            20.9
70  1942-10-15 1996-05-12  84.0          53.6            30.4
73  1958-04-07 2011-07-10  68.6          53.3            15.3
78  1942-10-15 1993-01-06  84.0          50.2            33.8
82  1948-03-03 2008-06-21  78.7          60.3            18.4
83  1944-02-16 2019-10-10  82.7          75.6             7.1
98  1970-10-24 1995-11-07  56.0          25.0            31.0
124 1955-02-02 2021-07-07  71.7          66.4             5.3

In [39]:
#Investigate the reference date used for AGE
reference_date = patients["BIRTHDATE"].max()
patients["EXPECTED_AGE"] = ( (reference_date - patients["BIRTHDATE"]).dt.days / 365.2425 ).round(1)
patients["AGE_CHECK_DIFFERENCE"] = ( patients["AGE"] - patients["EXPECTED_AGE"] ).round(1)
print("Reference date:", reference_date)
print("\nComparison of recorded and expected ages:") 
print( patients[ ["BIRTHDATE", "AGE", "EXPECTED_AGE", "AGE_CHECK_DIFFERENCE"] ].head(10) )
print("\nSummary of age differences:") 
print(patients["AGE_CHECK_DIFFERENCE"].describe())

Reference date: 2021-09-24 00:00:00

Comparison of recorded and expected ages:
   BIRTHDATE   AGE  EXPECTED_AGE  AGE_CHECK_DIFFERENCE
0 2019-02-17   7.7           2.6                   5.1
1 2005-07-04  21.3          16.2                   5.1
2 1998-05-11  28.5          23.4                   5.1
3 2003-01-28  23.7          18.7                   5.0
4 1993-12-23  32.8          27.8                   5.0
5 2020-12-04   5.9           0.8                   5.1
6 1990-12-15  35.9          30.8                   5.1
7 1985-06-05  41.4          36.3                   5.1
8 1979-12-17  46.9          41.8                   5.1
9 2006-07-11  20.3          15.2                   5.1

Summary of age differences:
count    1163.000000
mean        5.088650
std         0.031734
min         5.000000
25%         5.100000
50%         5.100000
75%         5.100000
max         5.100000
Name: AGE_CHECK_DIFFERENCE, dtype: float64

In [40]:
#Investigate whether AGE matches age calculated today
reference_date = pd.Timestamp.today().normalize()
patients["EXPECTED_AGE_TODAY"] = ( (reference_date - patients["BIRTHDATE"]).dt.days / 365.25 ).round(1)
patients["AGE_DIFFERENCE_TODAY"] = ( patients["AGE"] - patients["EXPECTED_AGE_TODAY"] ).round(1)
print("Reference date:", reference_date.date())
print("\nAge difference summary:") 
print(patients["AGE_DIFFERENCE_TODAY"].describe())
print("\nSample comparison:") 
print( patients[ ["BIRTHDATE", "AGE", "EXPECTED_AGE_TODAY", "AGE_DIFFERENCE_TODAY"] ].head(15).to_string(index=False) )

Reference date: 2026-10-27

Age difference summary:
count    1163.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: AGE_DIFFERENCE_TODAY, dtype: float64

Sample comparison:
 BIRTHDATE  AGE  EXPECTED_AGE_TODAY  AGE_DIFFERENCE_TODAY
2019-02-17  7.7                 7.7                   0.0
2005-07-04 21.3                21.3                   0.0
1998-05-11 28.5                28.5                   0.0
2003-01-28 23.7                23.7                   0.0
1993-12-23 32.8                32.8                   0.0
2020-12-04  5.9                 5.9                   0.0
1990-12-15 35.9                35.9                   0.0
1985-06-05 41.4                41.4                   0.0
1979-12-17 46.9                46.9                   0.0
2006-07-11 20.3                20.3                   0.0
1993-01-22 33.8                33.8                   0.0
1971-12-06 54.9                54.9                   0.0
1990-12-28 35.8                35.8                   0.0
1984-03-23 42.6                42.6                   0.0
1958-09-18 68.1                68.1                   0.0

In [42]:
#Display all columns related to encounters and dates
print("All dataset columns:") 
print(patients.columns.tolist())
print("\nColumns containing date or encounter terms:") 
print([ col for col in patients.columns if any(term in col.upper() for term in ["DATE", "TIME", "ENCOUNTER", "ADMIT", "VISIT", "START", "STOP"]) ])

All dataset columns:
['Id', 'BIRTHDATE', 'DEATHDATE', 'SSN', 'DRIVERS', 'PASSPORT', 'PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE', 'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE', 'COUNTY', 'ZIP', 'LAT', 'LON', 'HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE', 'AGE', 'EXPECTED_AGE', 'AGE_CHECK_DIFFERENCE', 'EXPECTED_AGE_TODAY', 'AGE_DIFFERENCE_TODAY']

Columns containing date or encounter terms:
['BIRTHDATE', 'DEATHDATE']

In [46]:
from pathlib import Path
#Find the project root
project = Path.cwd().parent
print("Project folder:", project) 
print("\nAll CSV files in the project:")
for file in project.rglob("*.csv"): 
    if ".venv" not in str(file) and "venv313" not in str(file): 
        print(file)

Project folder: c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics

All CSV files in the project:
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\allergies.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\careplans.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\claims.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\claims_transactions.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\conditions.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\devices.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\encounters.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\imaging_studies.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\immunizations.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\medications.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\observations.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\organizations.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\patients.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\payers.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\payer_transitions.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\procedures.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\providers.csv
c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\data\raw\csv\supplies.csv

In [49]:
import pandas as pd 
from pathlib import Path
#Locate the encounters file
project = Path.cwd().parent 
encounters_path = project / "data" / "raw" / "csv" / "encounters.csv"
#Load the dataset
encounters = pd.read_csv(encounters_path)
print("Encounters dataset shape:", encounters.shape)
print("\nColumn names:") 
print(encounters.columns.tolist())
print("\nFirst 5 encounters:") 
display(encounters.head())
print("\nData types and missing values:") 
display(encounters.info())

Encounters dataset shape: (61459, 15)

Column names:
['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PROVIDER', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION']

First 5 encounters:

,Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,748f8357-6cc7-551d-f31a-32fa2cf84126,2019-02-17T05:07:38Z,2019-02-17T05:22:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,877.79,833.90,NaN,NaN
1,5a4735ae-423f-6563-28ab-b3d11b49b2d4,2019-03-24T05:07:38Z,2019-03-24T05:22:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,269.68,256.20,NaN,NaN
2,0bee1ce6-3e2c-5506-f71c-a7ba8f64a3d3,2019-05-26T05:07:38Z,2019-05-26T05:22:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,1292.75,1228.11,NaN,NaN
3,6e93bcf9-45a4-8528-0120-1c1eaa930faf,2019-07-28T05:07:38Z,2019-07-28T05:22:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,1323.87,1257.68,NaN,NaN
4,8b6787c3-4316-a0cb-899d-4746525c319f,2019-10-27T05:07:38Z,2019-10-27T05:22:38Z,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,f7ae497d-8dc6-3721-9402-43b621a4e7d2,82608ebb-037c-3cef-9d34-3736d69b29e8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,831.76,790.17,NaN,NaN

Data types and missing values:
<class 'pandas.DataFrame'>
RangeIndex: 61459 entries, 0 to 61458
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   61459 non-null  str
 1   START                61459 non-null  str
 2   STOP                 61459 non-null  str
 3   PATIENT              61459 non-null  str
 4   ORGANIZATION         61459 non-null  str
 5   PROVIDER             61459 non-null  str
 6   PAYER                61459 non-null  str
 7   ENCOUNTERCLASS       61459 non-null  str
 8   CODE                 61459 non-null  int64
 9   DESCRIPTION          61459 non-null  str
 10  BASE_ENCOUNTER_COST  61459 non-null  float64
 11  TOTAL_CLAIM_COST     61459 non-null  float64
 12  PAYER_COVERAGE       61459 non-null  float64
 13  REASONCODE           15957 non-null  float64
 14  REASONDESCRIPTION    15957 non-null  str
dtypes: float64(4), int64(1), str(10)
memory usage: 7.0 MB

None

In [50]:
#Profile the encounters dataset
print("Dataset shape:", encounters.shape)
print("\nEncounter classes:") 
print(encounters["ENCOUNTERCLASS"].value_counts())
print("\nEncounter descriptions:") 
print(encounters["DESCRIPTION"].nunique(), "unique descriptions")
print("\nMissing values:") 
print(encounters.isnull().sum())
print("\nDuplicate encounter IDs:") 
print(encounters["Id"].duplicated().sum())
print("\nEncounter date range:") 
print("Start:", encounters["START"].min()) 
print("End:", encounters["START"].max())

Dataset shape: (61459, 15)

Encounter classes:
ENCOUNTERCLASS
wellness      24038
ambulatory    20124
outpatient    10837
urgentcare     2564
emergency      2168
inpatient      1728
Name: count, dtype: int64

Encounter descriptions:
59 unique descriptions

Missing values:
Id                         0
START                      0
STOP                       0
PATIENT                    0
ORGANIZATION               0
PROVIDER                   0
PAYER                      0
ENCOUNTERCLASS             0
CODE                       0
DESCRIPTION                0
BASE_ENCOUNTER_COST        0
TOTAL_CLAIM_COST           0
PAYER_COVERAGE             0
REASONCODE             45502
REASONDESCRIPTION      45502
dtype: int64

Duplicate encounter IDs:
0

Encounter date range:
Start: 1912-09-26T02:47:25Z
End: 2021-11-19T16:50:22Z

In [51]:
# Profile the encounters dataset

print("Dataset shape:", encounters.shape)

print("\nEncounter classes:")
print(encounters["ENCOUNTERCLASS"].value_counts())

print("\nEncounter descriptions:")
print(encounters["DESCRIPTION"].nunique(), "unique descriptions")

print("\nMissing values:")
print(encounters.isnull().sum())

print("\nDuplicate encounter IDs:")
print(encounters["Id"].duplicated().sum())

print("\nEncounter date range:")
print("Start:", encounters["START"].min())
print("End:", encounters["START"].max())

Dataset shape: (61459, 15)

Encounter classes:
ENCOUNTERCLASS
wellness      24038
ambulatory    20124
outpatient    10837
urgentcare     2564
emergency      2168
inpatient      1728
Name: count, dtype: int64

Encounter descriptions:
59 unique descriptions

Missing values:
Id                         0
START                      0
STOP                       0
PATIENT                    0
ORGANIZATION               0
PROVIDER                   0
PAYER                      0
ENCOUNTERCLASS             0
CODE                       0
DESCRIPTION                0
BASE_ENCOUNTER_COST        0
TOTAL_CLAIM_COST           0
PAYER_COVERAGE             0
REASONCODE             45502
REASONDESCRIPTION      45502
dtype: int64

Duplicate encounter IDs:
0

Encounter date range:
Start: 1912-09-26T02:47:25Z
End: 2021-11-19T16:50:22Z

In [53]:
#Check encounter data quality
#1. Check missing values in every column
print("Missing values in each column:") 
print(encounters.isnull().sum().to_string())
#2. Check duplicate encounter IDs
print("\nDuplicate encounter IDs:") 
print(encounters["Id"].duplicated().sum())
#3. Convert dates to datetime format for reliable analysis
encounters["START"] = pd.to_datetime(
     encounters["START"], errors="coerce", utc=True 
) 
encounters["STOP"] = pd.to_datetime( 
    encounters["STOP"], errors="coerce", utc=True 
    )
#4. Check the earliest and latest encounter dates
print("\nEncounter date range:") 
print("Earliest:", encounters["START"].min()) 
print("Latest:", encounters["START"].max())
#5. Inspect the earliest 10 encounters
print("\n10 earliest encounters:") 
print( encounters.sort_values("START")[ ["Id", "START", "STOP", "PATIENT", "ENCOUNTERCLASS"] ].head(10).to_string(index=False) )
#6. Check encounters where the end precedes the start
print("\nEncounters ending before they start:") 
print((encounters["STOP"] < encounters["START"]).sum())

Missing values in each column:
Id                         0
START                      0
STOP                       0
PATIENT                    0
ORGANIZATION               0
PROVIDER                   0
PAYER                      0
ENCOUNTERCLASS             0
CODE                       0
DESCRIPTION                0
BASE_ENCOUNTER_COST        0
TOTAL_CLAIM_COST           0
PAYER_COVERAGE             0
REASONCODE             45502
REASONDESCRIPTION      45502

Duplicate encounter IDs:
0

Encounter date range:
Earliest: 1912-09-26 02:47:25+00:00
Latest: 2021-11-19 16:50:22+00:00

10 earliest encounters:
                                  Id                     START                      STOP                              PATIENT ENCOUNTERCLASS
2a7317d9-b5c3-4bfa-56af-2870bb04b9cf 1912-09-26 02:47:25+00:00 1912-09-26 03:02:25+00:00 7bc66758-5d59-0b38-1532-29a33fa146c1     ambulatory
75e3238b-47f6-6fa1-e3e4-3258d1ca5c4c 1912-10-08 06:47:25+00:00 1912-10-08 07:02:25+00:00 7bc66758-5d59-0b38-1532-29a33fa146c1     ambulatory
9db53d29-29b2-f6e0-e2a2-26aaa1f82a44 1914-07-02 01:04:17+00:00 1914-07-02 01:19:17+00:00 b0332845-6c2a-bef0-04f1-8fc60ba829a5     ambulatory
3425d7dd-ebf1-4520-7b0d-882234b4255b 1914-07-20 14:04:17+00:00 1914-07-20 14:19:17+00:00 b0332845-6c2a-bef0-04f1-8fc60ba829a5     ambulatory
f665bc05-6734-dabd-aced-6cc075108427 1917-01-04 06:54:38+00:00 1917-01-04 07:09:38+00:00 b755085e-cb18-f1f0-d5f3-477b850a231b     ambulatory
b3038d26-7901-a25a-1404-c5c96712f127 1917-01-19 19:29:38+00:00 1917-01-19 19:44:38+00:00 b755085e-cb18-f1f0-d5f3-477b850a231b     ambulatory
9f05419d-9127-69e4-2320-c88b4334b893 1918-01-20 11:46:49+00:00 1918-01-20 12:01:49+00:00 3b26d1ac-6443-060d-d502-b93b8d82ccc2     ambulatory
b562ee8b-0a39-0874-40b0-af55ffef26a9 1918-02-03 06:58:49+00:00 1918-02-03 07:13:49+00:00 3b26d1ac-6443-060d-d502-b93b8d82ccc2     ambulatory
2e5270af-25a8-6b10-df25-e7c0a215cd13 1919-01-02 15:34:00+00:00 1919-01-02 15:49:00+00:00 e23c7a6e-6ef2-3932-1361-b73b4c8a3961     ambulatory
7c5ded8d-3abb-fd5a-a20c-bb1b26064c0f 1919-06-06 07:30:25+00:00 1919-06-06 09:32:15+00:00 acf7fc98-1e54-740b-953d-f111696e7e4e      emergency

Encounters ending before they start:
0

In [54]:
#Inspect the earliest encounters
encounters["START"] = pd.to_datetime( 
    encounters["START"], errors="coerce", utc=True 
)
encounters["STOP"] = pd.to_datetime( 
    encounters["STOP"], errors="coerce", utc=True 
)
print("Earliest 10 encounters:") 
display( 
    encounters.sort_values("START")[ 
        ["START", "STOP", "ENCOUNTERCLASS", "DESCRIPTION"] 
        ].head(10) 
)
print("\nEncounters before 1950:") 
display( 
    encounters.loc[ 
        encounters["START"].dt.year < 1950, 
        ["START", "STOP", "ENCOUNTERCLASS", "DESCRIPTION"] 
        ].head(20) 
)

Earliest 10 encounters:

,START,STOP,ENCOUNTERCLASS,DESCRIPTION
26691,1912-09-26 02:47:25+00:00,1912-09-26 03:02:25+00:00,ambulatory,Encounter for problem
26692,1912-10-08 06:47:25+00:00,1912-10-08 07:02:25+00:00,ambulatory,Encounter for problem
36416,1914-07-02 01:04:17+00:00,1914-07-02 01:19:17+00:00,ambulatory,Encounter for problem
36417,1914-07-20 14:04:17+00:00,1914-07-20 14:19:17+00:00,ambulatory,Encounter for problem
44940,1917-01-04 06:54:38+00:00,1917-01-04 07:09:38+00:00,ambulatory,Encounter for problem
44941,1917-01-19 19:29:38+00:00,1917-01-19 19:44:38+00:00,ambulatory,Encounter for problem
26436,1918-01-20 11:46:49+00:00,1918-01-20 12:01:49+00:00,ambulatory,Encounter for problem
26438,1918-02-03 06:58:49+00:00,1918-02-03 07:13:49+00:00,ambulatory,Encounter for problem
24644,1919-01-02 15:34:00+00:00,1919-01-02 15:49:00+00:00,ambulatory,Encounter for problem
42714,1919-06-06 07:30:25+00:00,1919-06-06 09:32:15+00:00,emergency,Emergency Room Admission

Encounters before 1950:

,START,STOP,ENCOUNTERCLASS,DESCRIPTION
3447,1949-07-02 07:54:43+00:00,1949-07-02 08:09:43+00:00,ambulatory,Encounter for problem
3449,1949-07-18 01:54:43+00:00,1949-07-18 02:09:43+00:00,ambulatory,Encounter for problem
4135,1948-11-04 20:54:43+00:00,1948-11-04 21:09:43+00:00,ambulatory,Encounter for problem
4136,1948-11-23 19:54:43+00:00,1948-11-23 20:09:43+00:00,ambulatory,Encounter for problem
4302,1945-02-19 05:33:35+00:00,1945-02-19 05:48:35+00:00,ambulatory,Encounter for problem
4303,1945-03-05 17:03:35+00:00,1945-03-05 17:18:35+00:00,ambulatory,Encounter for problem
7972,1937-10-02 15:13:14+00:00,1937-10-02 15:28:14+00:00,ambulatory,Encounter for symptom
9989,1935-07-01 00:39:29+00:00,1935-07-01 00:54:29+00:00,ambulatory,Encounter for symptom
9990,1935-08-26 00:39:29+00:00,1935-08-26 00:54:29+00:00,wellness,Well child visit (procedure)
9991,1936-02-24 00:39:29+00:00,1936-02-24 00:54:29+00:00,wellness,Well child visit (procedure)
9992,1936-08-24 00:39:29+00:00,1936-08-24 00:54:29+00:00,wellness,Well child visit (procedure)
9993,1937-04-12 00:39:29+00:00,1937-04-12 00:54:29+00:00,outpatient,Encounter for check up (procedure)
9994,1937-08-30 00:39:29+00:00,1937-08-30 00:54:29+00:00,wellness,Well child visit (procedure)
9995,1938-09-05 00:39:29+00:00,1938-09-05 00:54:29+00:00,wellness,Well child visit (procedure)
9996,1939-09-11 00:39:29+00:00,1939-09-11 00:54:29+00:00,wellness,Well child visit (procedure)
9997,1940-09-16 00:39:29+00:00,1940-09-16 00:54:29+00:00,wellness,Well child visit (procedure)
9998,1941-09-22 00:39:29+00:00,1941-09-22 00:54:29+00:00,wellness,Well child visit (procedure)
9999,1942-09-28 00:39:29+00:00,1942-09-28 00:54:29+00:00,wellness,Well child visit (procedure)
10000,1943-10-04 00:39:29+00:00,1943-10-04 00:54:29+00:00,wellness,Well child visit (procedure)
10001,1944-10-09 00:39:29+00:00,1944-10-09 00:54:29+00:00,wellness,Well child visit (procedure)

In [55]:
#Check the distribution of encounters by year
encounters["START_YEAR"] = encounters["START"].dt.year
print("Earliest year:", encounters["START"].dt.year.min()) 
print("Latest year:", encounters["START"].dt.year.max())
print("\nEncounters by year:") 
print(encounters["START_YEAR"].value_counts().sort_index().head(20))
print("\nEncounters by decade:") 
print( 
    (encounters["START"].dt.year // 10 * 10) 
    .value_counts() 
    .sort_index() 
)

Earliest year: 1912
Latest year: 2021

Encounters by year:
START_YEAR
1912     2
1914     2
1917     2
1918     2
1919     2
1921     3
1922     4
1923     3
1924     4
1925     5
1926     6
1927     5
1928    11
1929    16
1930    17
1931    37
1932    18
1933    22
1934    41
1935    48
Name: count, dtype: int64

Encounters by decade:
START
1910       10
1920       57
1930      359
1940      565
1950      883
1960     1590
1970     2944
1980     4380
1990     6128
2000     8889
2010    28165
2020     7489
Name: count, dtype: int64

In [56]:
#Examine encounter classes for records with missing reason codes
missing_reasons = encounters[ 
    encounters["REASONCODE"].isna() 
]
print("Encounters with missing reason codes:", 
      len(missing_reasons))

print("\nEncounter classes:") 
print(missing_reasons["ENCOUNTERCLASS"].value_counts())

print("\nEncounter descriptions:") 
print(missing_reasons["DESCRIPTION"].value_counts().head(15))

Encounters with missing reason codes: 45502

Encounter classes:
ENCOUNTERCLASS
wellness      23881
outpatient    10577
ambulatory     6222
urgentcare     2564
emergency      1335
inpatient       923
Name: count, dtype: int64

Encounter descriptions:
DESCRIPTION
General examination of patient (procedure)                          19374
Encounter for check up (procedure)                                   4778
Well child visit (procedure)                                         4507
Encounter for problem (procedure)                                    2577
Urgent care clinic (procedure)                                       2564
Outpatient procedure                                                 2010
Patient encounter procedure                                          1783
Consultation for treatment                                           1344
Administration of vaccine to produce active immunity (procedure)     1296
Encounter for problem                                                1198
Patient encounter procedure (procedure)                              1110
Emergency room admission (procedure)                                  790
Encounter for 'check-up'                                              638
Emergency Encounter                                                   443
Postnatal visit                                                       315
Name: count, dtype: int64

In [57]:
#Inspect the earliest encounters with patient identifiers
early_encounters = ( 
    encounters 
    .sort_values("START") 
    [["START", "STOP", "PATIENT", "ENCOUNTERCLASS", "DESCRIPTION"]] 
    .head(20) 
)
display(early_encounters)

,START,STOP,PATIENT,ENCOUNTERCLASS,DESCRIPTION
26691,1912-09-26 02:47:25+00:00,1912-09-26 03:02:25+00:00,7bc66758-5d59-0b38-1532-29a33fa146c1,ambulatory,Encounter for problem
26692,1912-10-08 06:47:25+00:00,1912-10-08 07:02:25+00:00,7bc66758-5d59-0b38-1532-29a33fa146c1,ambulatory,Encounter for problem
36416,1914-07-02 01:04:17+00:00,1914-07-02 01:19:17+00:00,b0332845-6c2a-bef0-04f1-8fc60ba829a5,ambulatory,Encounter for problem
36417,1914-07-20 14:04:17+00:00,1914-07-20 14:19:17+00:00,b0332845-6c2a-bef0-04f1-8fc60ba829a5,ambulatory,Encounter for problem
44940,1917-01-04 06:54:38+00:00,1917-01-04 07:09:38+00:00,b755085e-cb18-f1f0-d5f3-477b850a231b,ambulatory,Encounter for problem
44941,1917-01-19 19:29:38+00:00,1917-01-19 19:44:38+00:00,b755085e-cb18-f1f0-d5f3-477b850a231b,ambulatory,Encounter for problem
26436,1918-01-20 11:46:49+00:00,1918-01-20 12:01:49+00:00,3b26d1ac-6443-060d-d502-b93b8d82ccc2,ambulatory,Encounter for problem
26438,1918-02-03 06:58:49+00:00,1918-02-03 07:13:49+00:00,3b26d1ac-6443-060d-d502-b93b8d82ccc2,ambulatory,Encounter for problem
24644,1919-01-02 15:34:00+00:00,1919-01-02 15:49:00+00:00,e23c7a6e-6ef2-3932-1361-b73b4c8a3961,ambulatory,Encounter for problem
42714,1919-06-06 07:30:25+00:00,1919-06-06 09:32:15+00:00,acf7fc98-1e54-740b-953d-f111696e7e4e,emergency,Emergency Room Admission
42715,1921-02-25 07:30:25+00:00,1921-02-25 10:21:49+00:00,acf7fc98-1e54-740b-953d-f111696e7e4e,emergency,Emergency Room Admission
28297,1921-06-07 12:21:12+00:00,1921-06-07 13:21:12+00:00,c650efc6-4969-4cc7-65f7-bf8b59ca6421,emergency,Emergency room admission (procedure)
34105,1921-07-19 11:58:49+00:00,1921-07-19 13:45:35+00:00,83c5cc27-48a8-5580-966b-783719fe8f1b,emergency,Emergency Room Admission
57281,1922-03-19 05:51:58+00:00,1922-03-19 06:06:58+00:00,b6a7f9cd-340d-4289-ef69-12fdc928ad30,ambulatory,Encounter for symptom
42716,1922-05-27 07:30:25+00:00,1922-05-27 07:45:25+00:00,acf7fc98-1e54-740b-953d-f111696e7e4e,wellness,Well child visit (procedure)
37064,1922-06-13 21:04:17+00:00,1922-06-13 21:19:17+00:00,da88735b-1240-851d-d7d9-f42747fba5be,wellness,Well child visit (procedure)
54512,1922-08-13 16:46:25+00:00,1922-08-13 17:01:25+00:00,33ee607c-5afa-d4ff-85bc-3191531cf8c1,ambulatory,Encounter for symptom
48013,1923-07-13 15:56:07+00:00,1923-07-13 16:11:07+00:00,845a3922-0b68-9036-172a-57b58f1ff684,ambulatory,Encounter for symptom
48014,1923-10-03 15:56:07+00:00,1923-10-03 16:11:07+00:00,845a3922-0b68-9036-172a-57b58f1ff684,outpatient,Encounter for check up (procedure)
48015,1923-11-07 15:56:07+00:00,1923-11-07 16:11:07+00:00,845a3922-0b68-9036-172a-57b58f1ff684,wellness,Well child visit (procedure)

In [58]:
#Check how many encounters fall before 1950
print( 
    "Encounters before 1950:", 
    (encounters["START"].dt.year < 1950).sum() 
)
#Check encounters before 1980
print( 
    "Encounters before 1980:", 
    (encounters["START"].dt.year < 1980).sum() 
)

Encounters before 1950: 991
Encounters before 1980: 6408

In [59]:
from pathlib import Path
import pandas as pd

# Locate the project root from the notebook's working directory.
cwd = Path.cwd()

if cwd.name == "notebooks":
    project_root = cwd.parent
else:
    project_root = cwd

# Find the CSV files without changing the raw data.
def find_csv(filename):
    matches = [
        project_root / "data" / "raw" / "csv" / filename,
        project_root / "data" / "raw" / filename,
    ]

    for path in matches:
        if path.exists():
            return path

    raise FileNotFoundError(
        f"Could not find {filename}. "
        f"Looked in: {[str(p) for p in matches]}"
    )


# Load the two remaining tables and encounters.
conditions = pd.read_csv(find_csv("conditions.csv"))
payers = pd.read_csv(find_csv("payers.csv"))
encounters = pd.read_csv(find_csv("encounters.csv"))

# Profile a table.
def profile_table(df, table_name):
    print("\n" + "=" * 65)
    print(f"TABLE: {table_name.upper()}")
    print("=" * 65)

    print(f"Rows: {df.shape[0]:,}")
    print(f"Columns: {df.shape[1]:,}")

    print("\nColumn names:")
    print(df.columns.tolist())

    print("\nMissing values:")
    print(df.isna().sum().to_string())

    print(f"\nDuplicate rows: {df.duplicated().sum():,}")

    if "Id" in df.columns:
        print(f"Duplicate IDs: {df['Id'].duplicated().sum():,}")

    print("\nData types:")
    print(df.dtypes.to_string())


# Profile conditions.
profile_table(conditions, "conditions")

print("\nCONDITION DESCRIPTIONS — value_counts()")
print(conditions["DESCRIPTION"].value_counts(dropna=False).to_string())

# Profile payers.
profile_table(payers, "payers")

print("\nPAYER NAMES — value_counts()")
print(payers["NAME"].value_counts(dropna=False).to_string())

# Examine the condition STOP column.
if "STOP" in conditions.columns:
    missing_stop = conditions["STOP"].isna().sum()

    print("\nCONDITION STOP ANALYSIS")
    print(f"Missing STOP: {missing_stop:,}")
    print(
        f"Missing STOP (%): "
        f"{conditions['STOP'].isna().mean() * 100:.2f}%"
    )

# Check the selected analysis window.
encounters["START"] = pd.to_datetime(
    encounters["START"],
    errors="coerce",
    utc=True
)

window_start = pd.Timestamp("2011-01-01", tz="UTC")
window_end = pd.Timestamp("2022-01-01", tz="UTC")

in_window = (
    encounters["START"].ge(window_start)
    & encounters["START"].lt(window_end)
)

print("\n" + "=" * 65)
print("ANALYSIS WINDOW: 2011–2021")
print("=" * 65)

print(f"Total encounters: {len(encounters):,}")
print(f"Encounters retained: {in_window.sum():,}")
print(f"Encounters excluded before 2011: "
      f"{encounters['START'].lt(window_start).sum():,}")
print(f"Encounters excluded from 2022 onward: "
      f"{encounters['START'].ge(window_end).sum():,}")
print(f"Encounters with invalid or missing START: "
      f"{encounters['START'].isna().sum():,}")
print(f"Retention rate: {in_window.mean() * 100:.2f}%")

=================================================================
TABLE: CONDITIONS
=================================================================
Rows: 38,094
Columns: 6

Column names:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION']

Missing values:
START             0
STOP           8169
PATIENT           0
ENCOUNTER         0
CODE              0
DESCRIPTION       0

Duplicate rows: 0

Data types:
START            str
STOP             str
PATIENT          str
ENCOUNTER        str
CODE           int64
DESCRIPTION      str

CONDITION DESCRIPTIONS — value_counts()
DESCRIPTION
Full-time employment (finding)                                                      13805
Stress (finding)                                                                     5137
Part-time employment (finding)                                                       2426
Social isolation (finding)                                                           1243
Viral sinusitis (disorder)                                                           1233
Limited social contact (finding)                                                     1200
Not in labor force (finding)                                                         1077
Victim of intimate partner abuse (finding)                                            819
Acute viral pharyngitis (disorder)                                                    678
Acute bronchitis (disorder)                                                           571
Reports of violence in the environment (finding)                                      565
Normal pregnancy                                                                      527
Received higher education (finding)                                                   523
Body mass index 30+ - obesity (finding)                                               463
Risk activity involvement (finding)                                                   392
Prediabetes                                                                           341
Anemia (disorder)                                                                     324
Hypertension                                                                          292
Received certificate of high school equivalency (finding)                             265
Chronic sinusitis (disorder)                                                          219
Otitis media                                                                          217
Has a criminal record (finding)                                                       206
Miscarriage in first trimester                                                        204
Chronic low back pain (finding)                                                       195
Unhealthy alcohol drinking behavior (finding)                                         170
Streptococcal sore throat (disorder)                                                  162
Housing unsatisfactory (finding)                                                      154
Hyperlipidemia                                                                        138
Chronic neck pain (finding)                                                           123
Only received primary school education (finding)                                      123
Severe anxiety (panic) (finding                                                       120
Sprain of ankle                                                                       116
Transport problems (finding)                                                          107
Lack of access to transportation (finding)                                            104
Suspected COVID-19                                                                     96
COVID-19                                                                               92
Fever (finding)                                                                        86
Polyp of colon                                                                         85
Misuses drugs (finding)                                                                78
Unemployed (finding)                                                                   75
Acute bacterial sinusitis (disorder)                                                   74
Diabetes                                                                               73
Hypertriglyceridemia (disorder)                                                        71
Metabolic syndrome X (disorder)                                                        68
Coronary Heart Disease                                                                 65
Cough (finding)                                                                        62
Appendicitis                                                                           60
History of appendectomy                                                                60
Served in armed forces (finding)                                                       59
Osteoporosis (disorder)                                                                58
Osteoarthritis of knee                                                                 55
Sinusitis (disorder)                                                                   54
Concussion with no loss of consciousness                                               53
Refugee (person)                                                                       51
Stroke                                                                                 49
Seizure disorder                                                                       47
History of single seizure (situation)                                                  47
Whiplash injury to neck                                                                46
Fracture subluxation of wrist                                                          46
Chronic intractable migraine without aura                                              45
Atrial Fibrillation                                                                    44
Chronic pain                                                                           44
Sprain of wrist                                                                        43
Loss of taste (finding)                                                                42
Laceration of thigh                                                                    41
Fetus with unknown complication                                                        41
Hyperglycemia (disorder)                                                               41
Fracture of ankle                                                                      40
Fracture of forearm                                                                    40
Sepsis (disorder)                                                                      40
Impacted molars                                                                        40
Chronic congestive heart failure (disorder)                                            40
Laceration of foot                                                                     39
Cardiac Arrest                                                                         39
History of cardiac arrest (situation)                                                  39
Drug overdose                                                                          39
Alzheimer's disease (disorder)                                                         37
Escherichia coli urinary tract infection                                               36
Fracture of clavicle                                                                   35
Fatigue (finding)                                                                      35
Sputum finding (finding)                                                               35
Facial laceration                                                                      34
Laceration of forearm                                                                  32
Diabetic renal disease (disorder)                                                      31
Chronic kidney disease stage 1 (disorder)                                              30
Neoplasm of prostate                                                                   29
Epilepsy                                                                               28
Localized  primary osteoarthritis of the hand                                          28
Carcinoma in situ of prostate (disorder)                                               28
Laceration of hand                                                                     26
Fibromyalgia (disorder)                                                                26
Child attention deficit disorder                                                       25
Atopic dermatitis                                                                      25
Tubal pregnancy                                                                        24
Neuropathy due to type 2 diabetes mellitus (disorder)                                  24
Cystitis                                                                               23
Pneumonia (disorder)                                                                   23
Recurrent rectal polyp                                                                 23
Preeclampsia                                                                           22
Second degree burn                                                                     22
First degree burn                                                                      21
Antepartum eclampsia                                                                   21
Diabetic retinopathy associated with type II diabetes mellitus (disorder)              21
Concussion with loss of consciousness                                                  21
Hypoxemia (disorder)                                                                   20
Respiratory distress (finding)                                                         20
Childhood asthma                                                                       20
Pathological fracture due to osteoporosis (disorder)                                   20
Myocardial Infarction                                                                  20
History of myocardial infarction (situation)                                           20
Osteoarthritis of hip                                                                  19
Perennial allergic rhinitis                                                            19
Headache (finding)                                                                     19
Dyspnea (finding)                                                                      17
Wheezing (finding)                                                                     17
Malignant neoplasm of breast (disorder)                                                17
Homeless (finding)                                                                     17
Blighted ovum                                                                          17
Pneumonia                                                                              17
Pulmonary emphysema (disorder)                                                         16
Perennial allergic rhinitis with seasonal variation                                    16
Injury of tendon of the rotator cuff of shoulder                                       15
Body mass index 40+ - severely obese (finding)                                         14
Smokes tobacco daily                                                                   14
Nonproliferative diabetic retinopathy due to type 2 diabetes mellitus (disorder)       13
Chill (finding)                                                                        13
Rupture of appendix                                                                    13
Suspected lung cancer (situation)                                                      13
Non-small cell lung cancer (disorder)                                                  13
Sore throat symptom (finding)                                                          13
Non-small cell carcinoma of lung  TNM stage 1 (disorder)                               12
Chronic obstructive bronchitis (disorder)                                              12
Fracture of rib                                                                        12
Seasonal allergic rhinitis                                                             11
Closed fracture of hip                                                                 11
Muscle pain (finding)                                                                  11
Joint pain (finding)                                                                   11
Opioid abuse (disorder)                                                                11
Malignant tumor of colon                                                               10
Transformed migraine (disorder)                                                        10
Familial Alzheimer's disease of early onset (disorder)                                  9
Contact dermatitis                                                                      8
Acute allergic reaction                                                                 8
Primary fibromyalgia syndrome                                                           8
Gout                                                                                    8
Rupture of patellar tendon                                                              7
Concussion injury of brain                                                              7
Alcoholism                                                                              7
Bleeding from anus                                                                      6
Protracted diarrhea                                                                     6
Recurrent urinary tract infection                                                       6
Acute deep venous thrombosis (disorder)                                                 6
Acute respiratory failure (disorder)                                                    6
Shock (disorder)                                                                        6
Septic shock (disorder)                                                                 6
Injury of medial collateral ligament of knee                                            6
Sepsis caused by virus (disorder)                                                       5
Diarrhea symptom (finding)                                                              5
Bullet wound                                                                            5
Acute pulmonary embolism (disorder)                                                     5
Cerebral palsy (disorder)                                                               5
Spasticity (finding)                                                                    5
Idiopathic atrophic hypothyroidism                                                      5
Metastasis from malignant tumor of prostate (disorder)                                  5
Acute Cholecystitis                                                                     4
Cholelithiasis                                                                          4
Rheumatoid arthritis                                                                    4
Acute respiratory distress syndrome (disorder)                                          4
Intellectual disability (disorder)                                                      4
Gastroesophageal reflux disease (disorder)                                              4
Brain damage - traumatic                                                                4
Overlapping malignant neoplasm of colon                                                 4
Macular edema and retinopathy due to type 2 diabetes mellitus (disorder)                4
Injury of anterior cruciate ligament                                                    4
Nasal congestion (finding)                                                              4
Secondary malignant neoplasm of colon                                                   3
Hemoptysis (finding)                                                                    3
Epilepsy (disorder)                                                                     3
Nausea (finding)                                                                        3
Vomiting symptom (finding)                                                              3
Chronic paralysis due to lesion of spinal cord                                          3
Asthma                                                                                  2
Third degree burn                                                                       2
Pain (finding)                                                                          2
Poor muscle tone (finding)                                                              2
Primary malignant neoplasm of colon                                                     2
Tear of meniscus of knee                                                                1
Injury of kidney (disorder)                                                             1
Pyelonephritis                                                                          1
Chronic kidney disease stage 2 (disorder)                                               1
Microalbuminuria due to type 2 diabetes mellitus (disorder)                             1
At risk for suicide (finding)                                                           1
Dislocation of hip joint (disorder)                                                     1
Spina bifida occulta (disorder)                                                         1
Male Infertility                                                                        1
Cystic Fibrosis                                                                         1
Infection caused by Pseudomonas aeruginosa                                              1
Proliferative diabetic retinopathy due to type II diabetes mellitus (disorder)          1
Non-small cell carcinoma of lung  TNM stage 2 (disorder)                                1
History of lower limb amputation (situation)                                            1
Acquired coagulation disorder (disorder)                                                1
Injury of heart (disorder)                                                              1
Major depression disorder                                                               1
Fracture of the vertebral column with spinal cord injury                                1

=================================================================
TABLE: PAYERS
=================================================================
Rows: 10
Columns: 21

Column names:
['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE_HEADQUARTERED', 'ZIP', 'PHONE', 'AMOUNT_COVERED', 'AMOUNT_UNCOVERED', 'REVENUE', 'COVERED_ENCOUNTERS', 'UNCOVERED_ENCOUNTERS', 'COVERED_MEDICATIONS', 'UNCOVERED_MEDICATIONS', 'COVERED_PROCEDURES', 'UNCOVERED_PROCEDURES', 'COVERED_IMMUNIZATIONS', 'UNCOVERED_IMMUNIZATIONS', 'UNIQUE_CUSTOMERS', 'QOLS_AVG', 'MEMBER_MONTHS']

Missing values:
Id                         0
NAME                       0
ADDRESS                    1
CITY                       1
STATE_HEADQUARTERED        1
ZIP                        1
PHONE                      1
AMOUNT_COVERED             0
AMOUNT_UNCOVERED           0
REVENUE                    0
COVERED_ENCOUNTERS         0
UNCOVERED_ENCOUNTERS       0
COVERED_MEDICATIONS        0
UNCOVERED_MEDICATIONS      0
COVERED_PROCEDURES         0
UNCOVERED_PROCEDURES       0

In [60]:
from pathlib import Path

# Profile the four project tables.
patients = pd.read_csv(find_csv("patients.csv"))

# Reuse the encounters DataFrame already loaded above.
tables = {
    "patients": patients,
    "encounters": encounters,
    "conditions": conditions,
    "payers": payers,
}

# Define primary keys and relationships.
table_notes = {
    "patients": {
        "key": "Id",
        "joins": "Referenced by encounters.PATIENT.",
    },
    "encounters": {
        "key": "Id",
        "joins": (
            "encounters.PATIENT → patients.Id; "
            "conditions.ENCOUNTER → encounters.Id; "
            "encounters.PAYER → payers.Id."
        ),
    },
    "conditions": {
        "key": "Id",
        "joins": "conditions.ENCOUNTER → encounters.Id.",
    },
    "payers": {
        "key": "Id",
        "joins": "Referenced by encounters.PAYER.",
    },
}

lines = [
    "# Hospital Patient Analytics Dashboard",
    "",
    "## Data Profile",
    "",
    "### Dataset provenance",
    "",
    "The dataset consists of synthetic healthcare records generated by "
    "Synthea. The records do not represent real patients or real hospital "
    "operations.",
    "",
    "### Table overview",
    "",
    "| Table | Rows | Columns | Duplicate rows | Duplicate IDs | Primary key |",
    "|---|---:|---:|---:|---:|---|",
]

for name, df in tables.items():
    duplicate_rows = int(df.duplicated().sum())

    if "Id" in df.columns:
        duplicate_ids = int(df["Id"].duplicated().sum())
        primary_key = "Id"
    else:
        duplicate_ids = None
        primary_key = "Not identified"

    duplicate_ids_text = (
        f"{duplicate_ids:,}" if duplicate_ids is not None else "N/A"
    )

    lines.append(
        f"| {name} | {len(df):,} | {df.shape[1]:,} | "
        f"{duplicate_rows:,} | {duplicate_ids_text} | {primary_key} |"
    )

lines += [
    "",
    "### Table relationships",
    "",
    "| Table | Key | Relationship / join |",
    "|---|---|---|",
]

for name, df in tables.items():
    note = table_notes[name]
    lines.append(
        f"| {name} | `{note['key']}` | {note['joins']} |"
    )

for name, df in tables.items():
    lines += [
        "",
        f"### {name.title()}",
        "",
        f"- Rows: {len(df):,}",
        f"- Columns: {df.shape[1]:,}",
        f"- Exact duplicate rows: {df.duplicated().sum():,}",
        "",
        "#### Missing values by column",
        "",
        "| Column | Missing values | Missing (%) |",
        "|---|---:|---:|",
    ]

    missing_counts = df.isna().sum()

    for column, count in missing_counts.items():
        percentage = count / len(df) * 100 if len(df) else 0
        lines.append(
            f"| `{column}` | {count:,} | {percentage:.2f}% |"
        )

    if "Id" in df.columns:
        lines += [
            "",
            f"- Duplicate IDs: {df['Id'].duplicated().sum():,}",
        ]

    if name == "conditions":
        lines += [
            "",
            "#### Most frequent condition descriptions",
            "",
            "| Description | Count |",
            "|---|---:|",
        ]

        counts = df["DESCRIPTION"].value_counts(dropna=False)

        for description, count in counts.items():
            safe_description = str(description).replace("|", "\\|")
            lines.append(f"| {safe_description} | {count:,} |")

        if "STOP" in df.columns:
            missing_stop = int(df["STOP"].isna().sum())
            missing_stop_pct = df["STOP"].isna().mean() * 100

            lines += [
                "",
                f"Missing `STOP` values: {missing_stop:,} "
                f"({missing_stop_pct:.2f}%).",
                "",
                "Missing STOP values may indicate ongoing simulated "
                "conditions. They will be retained as null unless a "
                "specific analysis requires another treatment.",
            ]

    if name == "payers":
        lines += [
            "",
            "#### Payer name distribution",
            "",
            "| Payer name | Count |",
            "|---|---:|",
        ]

        counts = df["NAME"].value_counts(dropna=False)

        for payer_name, count in counts.items():
            safe_name = str(payer_name).replace("|", "\\|")
            lines.append(f"| {safe_name} | {count:,} |")

# Document the chosen analysis window.
valid_start = encounters["START"].notna()
in_window = (
    encounters["START"].ge(window_start)
    & encounters["START"].lt(window_end)
)

before_2011 = encounters["START"].lt(window_start)
after_2021 = encounters["START"].ge(window_end)

lines += [
    "",
    "## Analysis window",
    "",
    "**Selected window: 2011-01-01 to 2021-12-31, inclusive.**",
    "",
    "The dashboard describes a defined period of simulated hospital "
    "operations rather than each patient's entire lifetime history. "
    "The full source tables will be retained in the database; the "
    "window will be applied in SQL views and Power BI.",
    "",
    f"- Total encounters: {len(encounters):,}",
    f"- Encounters retained in the window: {int(in_window.sum()):,}",
    f"- Encounters before 2011: {int(before_2011.sum()):,}",
    f"- Encounters from 2022 onward: {int(after_2021.sum()):,}",
    f"- Encounters with missing or invalid START: "
    f"{int((~valid_start).sum()):,}",
    "",
    "Data-quality log decision: analysis window: 2011–2021; "
    f"{int(before_2011.sum()):,} encounters before 2011 excluded "
    "because the dashboard describes recent operations, not lifetime "
    "history. The full tables remain available for other analyses.",
    "",
    "## Interpretation and limitations",
    "",
    "- The dataset is synthetic and should not be interpreted as "
    "evidence about a real hospital or population.",
    "- Missing patient DEATHDATE values are treated as indicating that "
    "the patient was alive at the end of the simulation.",
    "- Missing encounter REASONCODE values are retained as null and "
    "will not be used in dashboard indicators. The top-ten diagnosis "
    "chart will be based on the conditions table.",
    "- Missing condition STOP values are retained as null because "
    "they can represent ongoing simulated conditions.",
    "- Identifier-like patient fields will be assessed for removal "
    "during the cleaning stage.",
    "",
    "## Scope of this profile",
    "",
    "This document records initial profiling results. It does not "
    "represent completion of the cleaning process. Date validation, "
    "relationship validation, and other cleaning decisions will be "
    "documented separately.",
]

docs_dir = project_root / "docs"
docs_dir.mkdir(parents=True, exist_ok=True)

profile_path = docs_dir / "data_profile.md"
profile_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

print(f"Created: {profile_path}")

Created: c:\Users\HP\OneDrive\Documents\Programming Portfolio\Hospital_Patient_Analytics\docs\data_profile.md